"""initial schema

Revision ID: d85e805acb04
Revises: 
Create Date: 2026-09-19 20:21:11.604844

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd85e805acb04'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('credential_profiles',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('protocol', sa.String(length=16), nullable=False),
    sa.Column('username', sa.String(length=128), nullable=True),
    sa.Column('encrypted_password', sa.LargeBinary(), nullable=True),
    sa.Column('encrypted_enable_password', sa.LargeBinary(), nullable=True),
    sa.Column('encrypted_ssh_private_key', sa.LargeBinary(), nullable=True),
    sa.Column('encrypted_snmp_community', sa.LargeBinary(), nullable=True),
    sa.Column('snmp_version', sa.String(length=8), nullable=True),
    sa.Column('snmp_v3_auth_protocol', sa.String(length=16), nullable=True),
    sa.Column('snmp_v3_priv_protocol', sa.String(length=16), nullable=True),
    sa.Column('encrypted_snmp_v3_auth_key', sa.LargeBinary(), nullable=True),
    sa.Column('encrypted_snmp_v3_priv_key', sa.LargeBinary(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('discovery_jobs',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('scope_cidrs', sa.JSON(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('config', sa.JSON(), nullable=False),
    sa.Column('total_targets', sa.Integer(), nullable=False),
    sa.Column('processed_targets', sa.Integer(), nullable=False),
    sa.Column('counts_by_type', sa.JSON(), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('finished_at', sa.DateTime(), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('devices',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('management_ip', sa.String(length=64), nullable=False),
    sa.Column('hostname', sa.String(length=255), nullable=True),
    sa.Column('vendor', sa.String(length=128), nullable=True),
    sa.Column('model', sa.String(length=128), nullable=True),
    sa.Column('os_name', sa.String(length=128), nullable=True),
    sa.Column('os_version', sa.String(length=128), nullable=True),
    sa.Column('uptime_seconds', sa.Integer(), nullable=True),
    sa.Column('device_type', sa.String(length=32), nullable=False),
    sa.Column('identification_confidence', sa.Float(), nullable=False),
    sa.Column('identification_sources', sa.JSON(), nullable=False),
    sa.Column('management_state', sa.String(length=32), nullable=False),
    sa.Column('available_management_methods', sa.JSON(), nullable=False),
    sa.Column('driver_type', sa.String(length=32), nullable=True),
    sa.Column('sys_object_id', sa.String(length=128), nullable=True),
    sa.Column('sys_descr', sa.Text(), nullable=True),
    sa.Column('default_credential_profile_id', sa.String(length=36), nullable=True),
    sa.Column('is_online', sa.Boolean(), nullable=False),
    sa.Column('first_seen', sa.DateTime(), nullable=False),
    sa.Column('last_seen', sa.DateTime(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['default_credential_profile_id'], ['credential_profiles.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('management_ip', name='uq_device_management_ip')
    )
    op.create_index(op.f('ix_devices_management_ip'), 'devices', ['management_ip'], unique=False)
    op.create_table('audit_events',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('operator', sa.String(length=128), nullable=False),
    sa.Column('action', sa.String(length=64), nullable=False),
    sa.Column('device_id', sa.String(length=36), nullable=True),
    sa.Column('protocol', sa.String(length=16), nullable=True),
    sa.Column('detail', sa.Text(), nullable=True),
    sa.Column('success', sa.Boolean(), nullable=False),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('source_session_id', sa.String(length=64), nullable=True),
    sa.ForeignKeyConstraint(['device_id'], ['devices.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_events_action'), 'audit_events', ['action'], unique=False)
    op.create_index(op.f('ix_audit_events_timestamp'), 'audit_events', ['timestamp'], unique=False)
    op.create_table('configuration_backups',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('device_id', sa.String(length=36), nullable=False),
    sa.Column('source', sa.String(length=16), nullable=False),
    sa.Column('driver_type', sa.String(length=32), nullable=False),
    sa.Column('operator', sa.String(length=128), nullable=False),
    sa.Column('file_path', sa.String(length=512), nullable=False),
    sa.Column('sha256', sa.String(length=64), nullable=False),
    sa.Column('byte_size', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('trigger', sa.String(length=32), nullable=False),
    sa.ForeignKeyConstraint(['device_id'], ['devices.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_configuration_backups_device_id'), 'configuration_backups', ['device_id'], unique=False)
    op.create_table('connections',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('source_device_id', sa.String(length=36), nullable=False),
    sa.Column('source_interface_name', sa.String(length=128), nullable=True),
    sa.Column('destination_device_id', sa.String(length=36), nullable=False),
    sa.Column('destination_interface_name', sa.String(length=128), nullable=True),
    sa.Column('discovery_methods', sa.JSON(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('first_observed', sa.DateTime(), nullable=False),
    sa.Column('last_observed', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['destination_device_id'], ['devices.id'], ),
    sa.ForeignKeyConstraint(['source_device_id'], ['devices.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_connection_pair', 'connections', ['source_device_id', 'destination_device_id'], unique=False)
    op.create_index(op.f('ix_connections_destination_device_id'), 'connections', ['destination_device_id'], unique=False)
    op.create_index(op.f('ix_connections_source_device_id'), 'connections', ['source_device_id'], unique=False)
    op.create_table('device_discovery_events',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('device_id', sa.String(length=36), nullable=False),
    sa.Column('source', sa.String(length=32), nullable=False),
    sa.Column('detail', sa.Text(), nullable=True),
    sa.Column('discovery_job_id', sa.String(length=36), nullable=True),
    sa.Column('observed_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['device_id'], ['devices.id'], ),
    sa.ForeignKeyConstraint(['discovery_job_id'], ['discovery_jobs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_device_discovery_events_device_id'), 'device_discovery_events', ['device_id'], unique=False)
    op.create_table('health_snapshots',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('device_id', sa.String(length=36), nullable=False),
    sa.Column('is_online', sa.Boolean(), nullable=False),
    sa.Column('cpu_percent', sa.Float(), nullable=True),
    sa.Column('memory_percent', sa.Float(), nullable=True),
    sa.Column('temperature_celsius', sa.Float(), nullable=True),
    sa.Column('uptime_seconds', sa.Integer(), nullable=True),
    sa.Column('icmp_rtt_ms', sa.Float(), nullable=True),
    sa.Column('collected_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['device_id'], ['devices.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_health_snapshots_collected_at'), 'health_snapshots', ['collected_at'], unique=False)
    op.create_index(op.f('ix_health_snapshots_device_id'), 'health_snapshots', ['device_id'], unique=False)
    op.create_table('interfaces',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('device_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('mac_address', sa.String(length=32), nullable=True),
    sa.Column('admin_state', sa.String(length=16), nullable=True),
    sa.Column('oper_state', sa.String(length=16), nullable=True),
    sa.Column('speed_mbps', sa.Integer(), nullable=True),
    sa.Column('duplex', sa.String(length=16), nullable=True),
    sa.Column('vlan', sa.String(length=32), nullable=True),
    sa.Column('rx_bytes', sa.Integer(), nullable=True),
    sa.Column('tx_bytes', sa.Integer(), nullable=True),
    sa.Column('rx_errors', sa.Integer(), nullable=True),
    sa.Column('tx_errors', sa.Integer(), nullable=True),
    sa.Column('in_discards', sa.Integer(), nullable=True),
    sa.Column('out_discards', sa.Integer(), nullable=True),
    sa.Column('if_index', sa.Integer(), nullable=True),
    sa.Column('last_polled', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['device_id'], ['devices.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('device_id', 'name', name='uq_interface_device_name')
    )
    op.create_index(op.f('ix_interfaces_device_id'), 'interfaces', ['device_id'], unique=False)
    op.create_table('routes',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('device_id', sa.String(length=36), nullable=False),
    sa.Column('destination', sa.String(length=64), nullable=False),
    sa.Column('prefix_length', sa.Integer(), nullable=False),
    sa.Column('next_hop', sa.String(length=64), nullable=True),
    sa.Column('interface_name', sa.String(length=128), nullable=True),
    sa.Column('protocol', sa.String(length=32), nullable=True),
    sa.Column('metric', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['device_id'], ['devices.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_routes_device_id'), 'routes', ['device_id'], unique=False)
    op.create_table('vlans',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('device_id', sa.String(length=36), nullable=False),
    sa.Column('vlan_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=True),
    sa.ForeignKeyConstraint(['device_id'], ['devices.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('device_id', 'vlan_id', name='uq_vlan_device_vlanid')
    )
    op.create_index(op.f('ix_vlans_device_id'), 'vlans', ['device_id'], unique=False)
    op.create_table('change_plans',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('operator', sa.String(length=128), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('proposed_config', sa.Text(), nullable=False),
    sa.Column('save_after_apply', sa.Boolean(), nullable=False),
    sa.Column('validation_report', sa.JSON(), nullable=True),
    sa.Column('diff_report', sa.JSON(), nullable=True),
    sa.Column('pre_change_backup_id', sa.String(length=36), nullable=True),
    sa.Column('post_change_backup_id', sa.String(length=36), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['post_change_backup_id'], ['configuration_backups.id'], ),
    sa.ForeignKeyConstraint(['pre_change_backup_id'], ['configuration_backups.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ip_addresses',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('interface_id', sa.String(length=36), nullable=False),
    sa.Column('address', sa.String(length=64), nullable=False),
    sa.Column('prefix_length', sa.Integer(), nullable=True),
    sa.Column('family', sa.String(length=8), nullable=False),
    sa.ForeignKeyConstraint(['interface_id'], ['interfaces.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ip_addresses_interface_id'), 'ip_addresses', ['interface_id'], unique=False)
    op.create_table('change_executions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('plan_id', sa.String(length=36), nullable=False),
    sa.Column('device_id', sa.String(length=36), nullable=False),
    sa.Column('apply_started_at', sa.DateTime(), nullable=True),
    sa.Column('apply_finished_at', sa.DateTime(), nullable=True),
    sa.Column('apply_success', sa.Boolean(), nullable=True),
    sa.Column('apply_output', sa.Text(), nullable=True),
    sa.Column('apply_error', sa.Text(), nullable=True),
    sa.Column('verified', sa.Boolean(), nullable=True),
    sa.Column('verification_detail', sa.Text(), nullable=True),
    sa.Column('rollback_status', sa.String(length=32), nullable=False),
    sa.Column('rollback_detail', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['device_id'], ['devices.id'], ),
    sa.ForeignKeyConstraint(['plan_id'], ['change_plans.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_change_executions_device_id'), 'change_executions', ['device_id'], unique=False)
    op.create_index(op.f('ix_change_executions_plan_id'), 'change_executions', ['plan_id'], unique=False)
    op.create_table('change_plan_devices',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('plan_id', sa.String(length=36), nullable=False),
    sa.Column('device_id', sa.String(length=36), nullable=False),
    sa.Column('eligible', sa.Boolean(), nullable=False),
    sa.Column('ineligibility_reason', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['device_id'], ['devices.id'], ),
    sa.ForeignKeyConstraint(['plan_id'], ['change_plans.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('plan_id', 'device_id', name='uq_plan_device')
    )
    op.create_index(op.f('ix_change_plan_devices_device_id'), 'change_plan_devices', ['device_id'], unique=False)
    op.create_index(op.f('ix_change_plan_devices_plan_id'), 'change_plan_devices', ['plan_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_change_plan_devices_plan_id'), table_name='change_plan_devices')
    op.drop_index(op.f('ix_change_plan_devices_device_id'), table_name='change_plan_devices')
    op.drop_table('change_plan_devices')
    op.drop_index(op.f('ix_change_executions_plan_id'), table_name='change_executions')
    op.drop_index(op.f('ix_change_executions_device_id'), table_name='change_executions')
    op.drop_table('change_executions')
    op.drop_index(op.f('ix_ip_addresses_interface_id'), table_name='ip_addresses')
    op.drop_table('ip_addresses')
    op.drop_table('change_plans')
    op.drop_index(op.f('ix_vlans_device_id'), table_name='vlans')
    op.drop_table('vlans')
    op.drop_index(op.f('ix_routes_device_id'), table_name='routes')
    op.drop_table('routes')
    op.drop_index(op.f('ix_interfaces_device_id'), table_name='interfaces')
    op.drop_table('interfaces')
    op.drop_index(op.f('ix_health_snapshots_device_id'), table_name='health_snapshots')
    op.drop_index(op.f('ix_health_snapshots_collected_at'), table_name='health_snapshots')
    op.drop_table('health_snapshots')
    op.drop_index(op.f('ix_device_discovery_events_device_id'), table_name='device_discovery_events')
    op.drop_table('device_discovery_events')
    op.drop_index(op.f('ix_connections_source_device_id'), table_name='connections')
    op.drop_index(op.f('ix_connections_destination_device_id'), table_name='connections')
    op.drop_index('ix_connection_pair', table_name='connections')
    op.drop_table('connections')
    op.drop_index(op.f('ix_configuration_backups_device_id'), table_name='configuration_backups')
    op.drop_table('configuration_backups')
    op.drop_index(op.f('ix_audit_events_timestamp'), table_name='audit_events')
    op.drop_index(op.f('ix_audit_events_action'), table_name='audit_events')
    op.drop_table('audit_events')
    op.drop_index(op.f('ix_devices_management_ip'), table_name='devices')
    op.drop_table('devices')
    op.drop_table('discovery_jobs')
    op.drop_table('credential_profiles')
    # ### end Alembic commands ###
